---
- name: Setup and run Gunicorn app on Amazon Linux
  hosts: sentimentalapp
  become: yes

  vars:
    app_dir: /opt/myapp
    venv_dir: /opt/myapp/venv
    git_user: "prakhers"
    git_repo: "github.com/PrakherS/sentiment-based-product-reco-system.git"
    gunicorn_cmd: "{{ venv_dir }}/bin/gunicorn app:app --bind 0.0.0.0:8000"

  vars_files:
    - vars/secrets.yaml

  tasks:

    - name: Install required packages
      yum:
        name:
          - git
          - python3
          - python3-pip
        state: present

    - name: Ensure application directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Clone the Sentimental repo
      git:
        repo: "https://{{ git_user }}:{{ git_token }}@{{ git_repo }}"
        dest: "{{ app_dir }}"
        clone: yes
        update: yes
        version: build-sentiment-model
      no_log: true

    - name: Create Python virtual environment
      command: python3 -m venv {{ venv_dir }}
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Upgrade pip inside virtualenv
      pip:
        name: pip
        state: latest
        virtualenv: "{{ venv_dir }}"

    - name: Install dependencies from requirements.txt
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"

    - name: Run Gunicorn application
      shell: |
        source {{ venv_dir }}/bin/activate
        {{ gunicorn_cmd }}
      args:
        chdir: "{{ app_dir }}"
      register: gunicorn_output
      async: 180 # Maximum time in seconds to run (e.g., 1 hour)
      poll: 0 # 0 means "fire and forget" (do not check status)

    - name: Print Gunicorn output
      debug:
        var: gunicorn_output
